@class NSString;

@interface _TtCs12_SwiftObject <NSObject> {
    Class isa;
    struct RefCounts<swift::RefCountBitsT<swift::RefCountIsInline>> { struct atomic<swift::RefCountBitsT<swift::RefCountIsInline>> { struct __cxx_atomic_impl<swift::RefCountBitsT<swift::RefCountIsInline>, std::__cxx_atomic_base_impl<swift::RefCountBitsT<swift::RefCountIsInline>>> { _Atomic struct RefCountBitsT<swift::RefCountIsInline> __a_value; } __a_; } refCounts; } refCounts;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (BOOL)_isDeallocating;
+ (void)release;
+ (BOOL)_tryRetain;
+ (id)alloc;
+ (id)allocWithZone:(struct _NSZone { } *)a0;
+ (BOOL)allowsWeakReference;
+ (id)autorelease;
+ (Class)class;
+ (BOOL)conformsToProtocol:(id)a0;
+ (id)debugDescription;
+ (id)description;
+ (void)initialize;
+ (void /* function */ *)instanceMethodForSelector:(SEL)a0;
+ (BOOL)instancesRespondToSelector:(SEL)a0;
+ (BOOL)isMemberOfClass:(Class)a0;
+ (BOOL)isSubclassOfClass:(Class)a0;
+ (void /* function */ *)methodForSelector:(SEL)a0;
+ (BOOL)respondsToSelector:(SEL)a0;
+ (id)retain;
+ (unsigned long long)retainCount;
+ (BOOL)retainWeakReference;
+ (Class)superclass;

- (id)safeSwiftOptionalCGPointForKey:(id)a0;
- (id)safeSwiftOptionalCGFloatForKey:(id)a0;
- (id)_safeSwiftDebugPrintAllFields;
- (id)safeSwiftArrayForKey:(id)a0;
- (BOOL)safeSwiftBoolForKey:(id)a0;
- (double)safeSwiftCGFloatForKey:(id)a0;
- (struct CGPoint { double x0; double x1; })safeSwiftCGPointForKey:(id)a0;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })safeSwiftCGRectForKey:(id)a0;
- (struct CGSize { double x0; double x1; })safeSwiftCGSizeForKey:(id)a0;
- (void)safeSwiftCallAsFunction:(id)a0;
- (id)safeSwiftDictionaryForKey:(id)a0;
- (double)safeSwiftDoubleForKey:(id)a0;
- (id)safeSwiftEnumAssociatedObject;
- (id)safeSwiftEnumCase;
- (float)safeSwiftFloatForKey:(id)a0;
- (short)safeSwiftInt16ForKey:(id)a0;
- (int)safeSwiftInt32ForKey:(id)a0;
- (long long)safeSwiftInt64ForKey:(id)a0;
- (char)safeSwiftInt8ForKey:(id)a0;
- (long long)safeSwiftIntForKey:(id)a0;
- (id)safeSwiftOptionalBoolForKey:(id)a0;
- (id)safeSwiftOptionalCGRectForKey:(id)a0;
- (id)safeSwiftOptionalCGSizeForKey:(id)a0;
- (id)safeSwiftOptionalDoubleForKey:(id)a0;
- (id)safeSwiftOptionalFloatForKey:(id)a0;
- (id)safeSwiftOptionalInt16ForKey:(id)a0;
- (id)safeSwiftOptionalInt32ForKey:(id)a0;
- (id)safeSwiftOptionalInt64ForKey:(id)a0;
- (id)safeSwiftOptionalInt8ForKey:(id)a0;
- (id)safeSwiftOptionalIntForKey:(id)a0;
- (id)safeSwiftOptionalUInt16ForKey:(id)a0;
- (id)safeSwiftOptionalUInt32ForKey:(id)a0;
- (id)safeSwiftOptionalUInt64ForKey:(id)a0;
- (id)safeSwiftOptionalUInt8ForKey:(id)a0;
- (id)safeSwiftOptionalUIntForKey:(id)a0;
- (id)safeSwiftSetForKey:(id)a0;
- (id)safeSwiftStringForKey:(id)a0;
- (unsigned short)safeSwiftUInt16ForKey:(id)a0;
- (unsigned int)safeSwiftUInt32ForKey:(id)a0;
- (unsigned long long)safeSwiftUInt64ForKey:(id)a0;
- (unsigned char)safeSwiftUInt8ForKey:(id)a0;
- (unsigned long long)safeSwiftUIntForKey:(id)a0;
- (id)safeSwiftValueForKey:(id)a0;
- (BOOL)_isDeallocating;
- (oneway void)release;
- (void)dealloc;
- (BOOL)isProxy;
- (void)_noteAssociatedObjects;
- (void)_setWeaklyReferenced;
- (BOOL)_tryRetain;
- (BOOL)allowsWeakReference;
- (id)autorelease;
- (Class)class;
- (BOOL)conformsToProtocol:(id)a0;
- (void)doesNotRecognizeSelector:(SEL)a0;
- (BOOL)isEqual:(id)a0;
- (BOOL)isKindOfClass:(Class)a0;
- (BOOL)isMemberOfClass:(Class)a0;
- (void /* function */ *)methodForSelector:(SEL)a0;
- (id)performSelector:(SEL)a0;
- (id)performSelector:(SEL)a0 withObject:(id)a1;
- (id)performSelector:(SEL)a0 withObject:(id)a1 withObject:(id)a2;
- (BOOL)respondsToSelector:(SEL)a0;
- (id)retain;
- (unsigned long long)retainCount;
- (BOOL)retainWeakReference;
- (id)self;
- (struct _NSZone { } *)zone;
- (BOOL)isNSCFConstantString__;
- (BOOL)isNSDate__;
- (BOOL)isNSNumber__;
- (BOOL)isNSString__;
- (unsigned long long)_cfTypeID;
- (id)_copyDescription;
- (BOOL)isNSArray__;
- (BOOL)isNSData__;
- (BOOL)isNSDictionary__;
- (BOOL)isNSObject__;
- (BOOL)isNSOrderedSet__;
- (BOOL)isNSSet__;
- (BOOL)isNSTimeZone__;
- (BOOL)isNSValue__;

@end
